* これは何か
  - iPhone上のPixiv Viewerは、フォロワーの新着から新着へ、フリックするだ
    けでカンタンに次から次へと絵が見れるのに、Web上ではそれができない。
  - それをやりたい。

* 基本的なアイデア
  1) 表示させる絵のリストを作成
  2) 絵の単独ページが開かれた時に、1)のリストを元に、
     前の絵、次の絵のアンカーをページに追加
  3) 2)は、アンカー追加じゃなくて、マウスジェスチャもしくは、ホイールス
     クロールで行ってもカッコイイかもしれない。

* 用語
  - イラストページ :: Pixivで、絵そのもののページ。つまり、URLが
		      =member_illust.php?mode=medium&illust_id=<illust_id>=
		      となっているページ。
  - フリックリスト :: イラストページには、同じ作者の時系列上での「次の絵」
                      「前の絵」のリンクしか表示されない。
		      しかし、例えば、
		      「フォロー新着作品」(=bookmark_new_illust.php=)や、
		      「マイピク新着作品」(=mypixiv_new_illust.php=)を経由
                      してイラストページを開いたユーザーにとっては、上記
                      リンクよりも「次のフォロー新着」や「次のマイピク新
                      着」のリンクを用意する方が合理的では無いのか？
		      その、合理的な「次」「前」のリンクを保持するリスト
                      のことを、本稿では「フリックリスト」と称する。

* 表示させる絵のリストの作成
** リストの元になる情報をどこから取得するか
   - 以下のページが開かれたときに、取得する。
     * =mypage.php=
     * =ranking.php=
     * =member_illust.php=
     * =tags.php=
     * =bookmark_new_illust.php=
     * =mypixiv_new_illust.php=

** TODO 取得したフリックリストをどこに記憶しておくか
   T.B.D.

** TODO 取得したリスト情報をどのタイミングで更新するのか。
   T.B.D.

* 課題
** TODO AutoPagerizeでページが継ぎ足されたとき、フリックリストをどう更新するか
   T.B.D.
   1) AutoPagerizeでページが継ぎ足されたとことが認識できれば、本拡張をキッ
      クすることができる。
   2) または、AutoPagerize自身にフックがあり、それを本拡張から書き換える
      ことができれば、本拡張をキックすることができる。
